name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # build at least once a month
    - cron: '0 0 1 * *'

jobs:
  appimage-x86_64:
    name: AppImage x86_64
    runs-on: ubuntu-16.04
    env:
      ARCH: x86_64
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build AppImage
        run: bash -ex ci/build-appimage.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: AppImage x86_64
          path: linuxdeploy-plugin-appimage*.AppImage*

  appimage-i386:
    name: AppImage i386
    runs-on: ubuntu-16.04
    env:
      ARCH: i386
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
            sudo dpkg --add-architecture i386
            sudo apt-get update
            sudo apt-get install -y g++-multilib libc6-dev:i386 libstdc++-5-dev:i386 zlib1g:i386 libfuse2:i386
      - name: Build AppImage
        run: bash -ex ci/build-appimage.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: AppImage i386
          path: linuxdeploy-plugin-appimage*.AppImage*

  appimage-aarch64:
    name: AppImage aarch64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          submodules: recursive
      - name: Build AppImage
        uses: uraimo/run-on-arch-action@v2.0.5
        with:
          arch: aarch64
          distro: ubuntu16.04
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --volume "${PWD}:/build"
          install: |
            apt update
            apt install -y build-essential wget
            wget -q -O cmake-install.sh https://github.com/Kitware/CMake/releases/download/v3.19.6/cmake-3.19.6-Linux-$(uname -m).sh
            sh cmake-install.sh --prefix=/usr --skip-license --exclude-subdir
            rm cmake-install.sh
          run: |
            cd /build
            ARCH=$(uname -m) ci/build-appimage.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: AppImage aarch64
          path: linuxdeploy-plugin-appimage*.AppImage*

  upload:
    name: Create release and upload artifacts
    needs:
      - appimage-x86_64
      - appimage-i386
      - appimage-aarch64
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Inspect directory after downloading artifacts
        run: ls -alFR
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
            chmod +x pyuploadtool-x86_64.AppImage
            ./pyuploadtool-x86_64.AppImage **/linuxdeploy-plugin-appimage*.AppImage*
